export const GET_USERS_REQUEST = 'GET_USERS_LOADING';
export const GET_USERS_RECEIVE = 'GET_USERS_LOADED';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_LOADING';
export const DELETE_USER_RECEIVE = 'DELETE_USER_LOADED';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const PUT_USER_REQUEST = 'PUT_USER_LOADING';
export const PUT_USER_RECEIVE = 'PUT_USER_LOADED';
export const PUT_USER_FAILURE = 'PUT_USER_FAILURE';

export const POST_USER_REQUEST = 'POST_USER_LOADING';
export const POST_USER_RECEIVE = 'POST_USER_LOADED';
export const POST_USER_FAILURE = 'POST_USER_FAILURE';